name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ./cl-string-generator
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Install Rove
      run: ros install rove
    - name: Run tests
      run: |
        PATH="~/.roswell/bin:$PATH"
        mkdir -p ~/.roswell/local-projects/pokepay
        mv $GITHUB_WORKSPACE/cl-string-generator ~/.roswell/local-projects/pokepay/cl-string-generator
        cd ~/.roswell/local-projects/pokepay/cl-string-generator
        rove cl-string-generator.asd
        
